openapi: "3.0.0"
info:
  description: "SimpleHelloWorld"
  version: "1.0.0"
  title: "HelloWorldPSD"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "pierluigi.plebani@polimi.it"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - url: http://api.psd.com/v1
    description: production server
  - url: http://localhost:9090/
    description: dev server

paths:
  /hello:
    get:
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema: 
                type: "string"
        400:
          description: "Invalid status value"
  /hello/{user}:
    get:
      parameters:
        - in: path
          name: user
          schema: 
            type: string
          required: true
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema: 
                type: "string"
        400:
          description: "Invalid status value"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"